# This is a placeholder so actions won't default to a getting started page

name: Placeholder

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
        
  documentation:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create docs folder
        run: mkdir docs
      - name: Convert md to html
        uses: docker://pandoc/core:2.9
        with:
          args: userguide.md -t html -o docs/index.html
      - name: Deploy Pages site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
